# Form implementation generated from reading ui file 'e:\PROJECTS-VSCODE\AppDesktopRandomForest\Formulario.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 511)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1050, 780, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1140, 780, 201, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 491, 81))
        self.frame_2.setStyleSheet("background-color: rgb(134, 153, 160);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_15.setGeometry(QtCore.QRect(40, 30, 75, 21))
        self.pushButton_15.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_15.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat Medium\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(150, 30, 75, 23))
        self.pushButton_16.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat Medium\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_17.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.pushButton_17.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat Medium\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_18.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.pushButton_18.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat Medium\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 80, 491, 391))
        self.frame.setStyleSheet("background-color: rgb(252, 249, 242);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_19.setGeometry(QtCore.QRect(350, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("background-color: rgb(56, 77, 89);\n"
"color: rgb(252, 249, 242);\n"
"border: none;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(260, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: rgb(56, 77, 89);\n"
"color: rgb(252, 249, 242);\n"
"border: none;\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 40, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(252, 249, 242);\n"
"color: rgb(56, 77, 89);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 80, 291, 181))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame.raise_()
        self.pushButton_11.raise_()
        self.pushButton_10.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_11.setText(_translate("MainWindow", "ATRAS"))
        self.pushButton_10.setText(_translate("MainWindow", "CARGAR NUEVO CONJUNTO DE DATOS"))
        self.pushButton_15.setText(_translate("MainWindow", "Subir Data"))
        self.pushButton_16.setText(_translate("MainWindow", "Parametros"))
        self.pushButton_17.setText(_translate("MainWindow", "Analisis"))
        self.pushButton_18.setText(_translate("MainWindow", "Formulario"))
        self.pushButton_19.setText(_translate("MainWindow", "Siguiente"))
        self.pushButton_14.setText(_translate("MainWindow", "Atras"))
        self.pushButton_3.setText(_translate("MainWindow", "Predecir"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
