# Form implementation generated from reading ui file 'e:\PROJECTS-VSCODE\AppDesktopRandomForest\Parametros.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 472)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 571, 81))
        self.frame_2.setStyleSheet("background-color: rgb(134, 153, 160);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.menu11 = QtWidgets.QPushButton(parent=self.frame_2)
        self.menu11.setGeometry(QtCore.QRect(40, 30, 75, 21))
        self.menu11.setMaximumSize(QtCore.QSize(75, 16777215))
        self.menu11.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat SemiBold\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.menu11.setObjectName("menu11")
        self.menu22 = QtWidgets.QPushButton(parent=self.frame_2)
        self.menu22.setGeometry(QtCore.QRect(150, 30, 75, 23))
        self.menu22.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat SemiBold\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.menu22.setObjectName("menu22")
        self.menu33 = QtWidgets.QPushButton(parent=self.frame_2)
        self.menu33.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.menu33.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat SemiBold\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.menu33.setObjectName("menu33")
        self.menu44 = QtWidgets.QPushButton(parent=self.frame_2)
        self.menu44.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.menu44.setStyleSheet("QWidget {\n"
"    background-color: rgb(208, 229, 214);\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 57 7pt \"Montserrat SemiBold\";\n"
"    color: rgb(56, 77, 89);\n"
"    border:none;\n"
"}")
        self.menu44.setObjectName("menu44")
        self.frame2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(0, 80, 571, 371))
        self.frame2.setStyleSheet("background-color: rgb(252, 249, 242);")
        self.frame2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame2.setObjectName("frame2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame2)
        self.label_9.setGeometry(QtCore.QRect(60, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(252, 249, 242);\n"
"color: rgb(56, 77, 89);")
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(parent=self.frame2)
        self.label_4.setGeometry(QtCore.QRect(290, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(252, 249, 242);\n"
"color: rgb(56, 77, 89);")
        self.label_4.setObjectName("label_4")
        self.menuatras2 = QtWidgets.QPushButton(parent=self.frame2)
        self.menuatras2.setGeometry(QtCore.QRect(330, 330, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.menuatras2.setFont(font)
        self.menuatras2.setStyleSheet("background-color: rgb(56, 77, 89);\n"
"color: rgb(252, 249, 242);\n"
"border: none;\n"
"")
        self.menuatras2.setObjectName("menuatras2")
        self.menusiguente2 = QtWidgets.QPushButton(parent=self.frame2)
        self.menusiguente2.setGeometry(QtCore.QRect(420, 330, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.menusiguente2.setFont(font)
        self.menusiguente2.setStyleSheet("background-color: rgb(56, 77, 89);\n"
"color: rgb(252, 249, 242);\n"
"border: none;")
        self.menusiguente2.setObjectName("menusiguente2")
        self.selectpredictor = QtWidgets.QComboBox(parent=self.frame2)
        self.selectpredictor.setGeometry(QtCore.QRect(300, 80, 191, 22))
        self.selectpredictor.setStyleSheet("background-color: rgb(208, 229, 214);\n"
"border:none;\n"
"")
        self.selectpredictor.setObjectName("selectpredictor")
        self.guardarparametros = QtWidgets.QPushButton(parent=self.frame2)
        self.guardarparametros.setGeometry(QtCore.QRect(420, 220, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.guardarparametros.setFont(font)
        self.guardarparametros.setStyleSheet("background-color: rgb(252, 249, 242);\n"
"color: rgb(56, 77, 89);\n"
"")
        self.guardarparametros.setObjectName("guardarparametros")
        self.listWidget = QtWidgets.QListWidget(parent=self.frame2)
        self.listWidget.setGeometry(QtCore.QRect(10, 80, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 80, 261, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame2.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu11.setText(_translate("MainWindow", "Subir Data"))
        self.menu22.setText(_translate("MainWindow", "Parametros"))
        self.menu33.setText(_translate("MainWindow", "Analisis"))
        self.menu44.setText(_translate("MainWindow", "Formulario"))
        self.label_9.setText(_translate("MainWindow", "Variables Independeintes"))
        self.label_4.setText(_translate("MainWindow", "Variable Predictor seleciciona"))
        self.menuatras2.setText(_translate("MainWindow", "Atras"))
        self.menusiguente2.setText(_translate("MainWindow", "Siguiente"))
        self.guardarparametros.setText(_translate("MainWindow", "Guardar"))
